//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BiZhi {
            get {
                object obj = ResourceManager.GetObject("BiZhi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] login_history {
            get {
                object obj = ResourceManager.GetObject("login_history", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 一个登录注册系统的架构通常包含以下几个核心类：
        ///1.User
        ///：表示用户的实体类，包含用户的基本信息，如用户名、密码等。
        ///2.UserDAO
        ///：数据访问对象类，负责与数据库进行交互，包括用户的增删改查操作。
        ///3.AuthenticationService
        ///：认证服务类，负责处理用户登录认证的逻辑，包括验证用户身份、生成和验证令牌等。
        ///4.RegistrationService
        ///：注册服务类，负责处理用户注册的逻辑，包括验证注册信息的有效性、添加用户到数据库等。
        ///5.PasswordHelper
        ///：密码辅助类，负责密码加密、解密等操作，以确保用户密码的安全性。
        ///6.UserInterface
        ///：用户界面类，负责与用户交互，包括显示登录界面、注册界面，接收用户输入等。
        ///7.ErrorHandler
        ///：错误处理类，负责处理系统中可能出现的异常情况，提供错误提示信息给用户或记录日志等。
        ///8.SessionManager
        ///：会话管理类，负责管理用户的登录状态和会话信息，包括创建、销毁会话等操作。
        ///9.Validator
        ///：验证器类，负责验证用户输入的数据是否合法，如用户名是否已存在、密码是否符合规范等。
        ///10.Emai [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 登录系统架构 {
            get {
                return ResourceManager.GetString("登录系统架构", resourceCulture);
            }
        }
    }
}
